services:
  - type: web
    name: hate-chat-backend
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: API_URL
        value: https://hate-chat-backend.onrender.com

    
    
  - type: static
    name: hate-chat-frontend
    buildCommand: ""
    staticPublishPath: frontend
    plan: free



